.Preface

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work.
====

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract

AIM is a multi-tier and modular domain model aligning, profiling, and/or extending well known agriculture related and generic ontologies, including existing ontologies published by the OGC. Recognizing that this is an innovative approach to publish such a domain model as a modular ontology the SWG will address both identification of best practices for this specialization approach and the development of a series of complementary models.

AIM provides a common language for agriculture applications to harmonize and improve data and metadata exchange by defining the data elements, including concepts, properties, and relationships relevant to agriculture applications, as well as their associated semantics/meaning for information exchange.

AIM is published as both human and implementation-ready machine-actionable resources. Machine-actionable resources include the canonical ontology representation of the AIM in the Web Ontology Language (OWL) as well as other related artifacts to support implementation.

The SWG will develop implementations of the AIM model compatible with OGC APIs, including:

* JSON schemas supported by OGC APIS;
* JSON-LD contexts allowing identification and validation of AIM-compliant data; and
* SHACL shapes enabling the validation of data against AIM semantics.

In addition, other forms may be derived or supplied to support reusability of the AIM model, according to requirements identified by the SWG:

* UML representation of AIM conceptual model;
* UML representation of one or more logical models for AIM implementation; and

Formal profiles for implementation of AIM using GeoJSON, FG-JSON, CoverageJSON, and other relevant generic schemas

In line with OGC policies and FAIR principles, the AIM will be published using persistent and resolvable URI identifiers, consistent with OGC Naming Authority processes for publishing semantic resources.

== Keywords

agriculture, data model

== Preface

[NOTE]
====
The Agriculture Information Model was initially developed in the Demeter project and used as the common reference ontology for the multi-actor System of Systems.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====

== Security considerations

//If no security considerations have been made for this Standard, use the following text.

No security considerations have been made for this Standard.

////
If security considerations have been made for this Standard, follow the examples found in IANA or IETF documents. Please see the following example.
“VRRP is designed for a range of internetworking environments that may employ different security policies. The protocol includes several authentication methods ranging from no authentication, simple clear text passwords, and strong authentication using IP Authentication with MD5 HMAC. The details on each approach including possible attacks and recommended environments follows.
Independent of any authentication type VRRP includes a mechanism (setting TTL=255, checking on receipt) that protects against VRRP packets being injected from another remote network. This limits most vulnerabilities to local attacks.
NOTE: The security measures discussed in the following sections only provide various kinds of authentication. No confidentiality is provided at all. This should be explicitly described as outside the scope....”
////

== Submitting organizations

// Submitting organizations inserted here by Metanorma

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
| name of the person | Organisation X
|===

== Contributors

//This clause is optional.

Additional contributors to this Standard include the following:

Individual name(s), Organization
