curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/cross-domain.ttl\" ]}" > cross-domain-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriCommon.ttl\" ]}" > agriCommon-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriFeature.ttl\" ]}" > agriFeature-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriCrop.ttl\" ]}" > agriCrop-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriIntervention.ttl\" ]}" > agriIntervention-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriAlert.ttl\" ]}" > agriAlert-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriProduct.ttl\" ]}" > agriProduct-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriProperty.ttl\" ]}" > agriProperty-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriSystem.ttl\" ]}" > agriSystem-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriPest.ttl\" ]}" > agriPest-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/farmAnimal.ttl\" ]}" > farmAnimal-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/cross-domain.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriCommon.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriFeature.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriCrop.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriIntervention.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriAlert.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriProduct.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriProperty.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriSystem.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/agriPest.ttl\", \"https://raw.githubusercontent.com/opengeospatial/aim-swg/main/farmAnimal.ttl\" ]}" > demeterAgriProfile-SHACL.ttl